<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PositionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('positions')->delete();

        \DB::table('positions')->insert(array (
            0 =>
            array (
                'id' => '92149720',
                'name' => 'Pelaksana Budgeting',
                'alias' => 'Staf Budgeting',
                'user_id' => '10760005',
                'group_id' => NULL,
                'grade' => 'A5.2',
                'hierarchy' => 60,
                'type' => 1,
                'unit' => 'WKFC',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            1 =>
            array (
                'id' => '92149722',
                'name' => 'Pelaksana Accounting',
                'alias' => 'Pelaksana Accounting',
                'user_id' => '13850030',
                'group_id' => NULL,
                'grade' => 'A5.2',
                'hierarchy' => 61,
                'type' => 1,
                'unit' => 'WKFC',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            2 =>
            array (
                'id' => '92149761',
                'name' => 'Pengawas Lapangan',
                'alias' => 'Pengawas Lapangan',
                'user_id' => '18930108',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 22,
                'type' => 1,
                'unit' => 'WOT',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            3 =>
            array (
                'id' => '92150368',
                'name' => 'Pengawas Lapangan',
                'alias' => 'Pengawas Lapangan',
                'user_id' => '19930281',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 105,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            4 =>
            array (
                'id' => '92150369',
                'name' => 'Pengawas Lapangan',
                'alias' => 'Pengawas Lapangan',
                'user_id' => '19930282',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 104,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            5 =>
            array (
                'id' => '92150373',
                'name' => 'Pengawas Lapangan',
                'alias' => 'Pengawas Lapangan',
                'user_id' => '19930277',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 98,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            6 =>
            array (
                'id' => '92150374',
                'name' => 'Pengawas Lapangan',
                'alias' => 'Pengawas Lapangan',
                'user_id' => '19930278',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 97,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            7 =>
            array (
                'id' => '92150375',
                'name' => 'Pengawas Lapangan',
                'alias' => 'Pengawas Lapangan',
                'user_id' => '19930275',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 95,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            8 =>
            array (
                'id' => '92150376',
                'name' => 'Pengawas Lapangan',
                'alias' => 'Pengawas Lapangan',
                'user_id' => '19930276',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 94,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            9 =>
            array (
                'id' => '92150377',
                'name' => 'Pengawas Lapangan',
                'alias' => 'Pengawas Lapangan',
                'user_id' => '19930176',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 93,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            10 =>
            array (
                'id' => '92150388',
                'name' => 'Staf Tour Mice',
                'alias' => 'Staf Tour Mice',
                'user_id' => '17920083',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 12,
                'type' => 1,
                'unit' => 'WOMT',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            11 =>
            array (
                'id' => '92150397',
                'name' => 'Pengawas Lapangan',
                'alias' => 'Pengawas Lapangan',
                'user_id' => '19930336',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 90,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            12 =>
            array (
                'id' => '92150407',
                'name' => 'Staf Ticketing',
                'alias' => 'Staf Ticketing',
                'user_id' => '19930166',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 69,
                'type' => 1,
                'unit' => 'WUC',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            13 =>
            array (
                'id' => '92150410',
                'name' => 'Driver Direksi',
                'alias' => 'Driver Direksi',
                'user_id' => '18810102',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 70,
                'type' => 1,
                'unit' => 'WUC',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            14 =>
            array (
                'id' => '92150919',
                'name' => 'Pengawas Lapangan',
                'alias' => 'Pengawas Lapangan',
                'user_id' => '19930271',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 100,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            15 =>
            array (
                'id' => '92151363',
                'name' => 'Pengawas Lapangan',
                'alias' => 'Pengawas Lapangan',
                'user_id' => '19930273',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 91,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            16 =>
            array (
                'id' => '92151460',
                'name' => 'Pengawas Lapangan',
                'alias' => 'Pengawas Lapangan',
                'user_id' => '19930272',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 99,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            17 =>
            array (
                'id' => '92159847',
                'name' => 'Pengawas Lapangan',
                'alias' => 'Pengawas Lapangan',
                'user_id' => '18900136',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 21,
                'type' => 1,
                'unit' => 'WOT',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            18 =>
            array (
                'id' => '92159860',
                'name' => 'Pelaksana Luxury Coach',
                'alias' => 'Pelaksana Luxury Coach',
                'user_id' => '12860023',
                'group_id' => NULL,
                'grade' => 'A5.2',
                'hierarchy' => 30,
                'type' => 1,
                'unit' => 'WOL',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            19 =>
            array (
                'id' => '92160098',
                'name' => 'Staf Finance ',
                'alias' => 'Staf Finance ',
                'user_id' => '19930331',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 63,
                'type' => 1,
                'unit' => 'WKFC',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            20 =>
            array (
                'id' => '92162076',
                'name' => 'Pengawas Lapangan Area 1 Daop 1',
                'alias' => 'Pengawas Lapangan Area 1 Daop 1',
                'user_id' => '19930267',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 84,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            21 =>
            array (
                'id' => '92162077',
                'name' => 'Pengawas Lapangan Area 1 Daop 1',
                'alias' => 'Pengawas Lapangan Area 1 Daop 1',
                'user_id' => '19930289',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 83,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            22 =>
            array (
                'id' => '92162300',
                'name' => 'Pengawas Lapangan Area 4 Divre I',
                'alias' => 'Pengawas Lapangan Area 4 Divre I',
                'user_id' => '19930285',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 111,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            23 =>
            array (
                'id' => '92162301',
                'name' => 'Pengawas Lapangan Area 4 Divre I',
                'alias' => 'Pengawas Lapangan Area 4 Divre I',
                'user_id' => '19930286',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 110,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            24 =>
            array (
                'id' => '92162303',
                'name' => 'Pengawas Lapangan Area 4 Divre III',
                'alias' => 'Pengawas Lapangan Area 4 Divre III',
                'user_id' => '19930288',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 108,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            25 =>
            array (
                'id' => '92162305',
                'name' => 'Pengawas Lapangan Area 4 Divre IV',
                'alias' => 'Pengawas Lapangan Area 4 Divre IV',
                'user_id' => '19930327',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 112,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            26 =>
            array (
                'id' => '92162340',
                'name' => 'Pengawas Lapangan Area 3 Daop 9',
                'alias' => 'Pengawas Lapangan Area 3 Daop 9',
                'user_id' => '19930284',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 106,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            27 =>
            array (
                'id' => '92166476',
                'name' => 'Pengawas Lapangan Area 1 KCI',
                'alias' => 'Pengawas Lapangan Area 1 KCI',
                'user_id' => '19930269',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 87,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            28 =>
            array (
                'id' => '92166477',
                'name' => 'Pengawas Lapangan Area 1 KCI',
                'alias' => 'Pengawas Lapangan Area 1 KCI',
                'user_id' => '19930268',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 88,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            29 =>
            array (
                'id' => '92176018',
                'name' => 'Senior Specialist Sales & Marketing',
                'alias' => 'Senior Specialist Sales & Marketing',
                'user_id' => '19850150',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 32,
                'type' => 1,
                'unit' => 'WOL',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            30 =>
            array (
                'id' => '92177097',
                'name' => 'Pengawas Lapangan Area 3 Daop 8',
                'alias' => 'Pengawas Lapangan Area 3 Daop 8',
                'user_id' => '19930283',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 103,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            31 =>
            array (
                'id' => '92177151',
                'name' => 'Trainer',
                'alias' => 'Trainer',
                'user_id' => '19650153',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 66,
                'type' => 1,
                'unit' => 'WKFH',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            32 =>
            array (
                'id' => '92177319',
                'name' => 'Travel Experience',
                'alias' => 'Travel Experience',
                'user_id' => '19970155',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 78,
                'type' => 1,
                'unit' => 'WUCB',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            33 =>
            array (
                'id' => '92178476',
                'name' => 'Pengawas Lapangan Area 1 KCI',
                'alias' => 'Pengawas Lapangan Area 1 KCI',
                'user_id' => '19930270',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 86,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            34 =>
            array (
                'id' => '92181622',
                'name' => 'M Historical Building And Museum',
                'alias' => 'Manager Historical Building And Museum',
                'user_id' => '40873',
                'group_id' => NULL,
                'grade' => 'M2.2',
                'hierarchy' => 3,
                'type' => 1,
                'unit' => 'WOHM',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            35 =>
            array (
                'id' => '92181629',
                'name' => 'GM Hospitality',
                'alias' => 'General Manager Hospitality',
                'user_id' => '64868',
                'group_id' => NULL,
                'grade' => 'M1.2',
                'hierarchy' => 2,
                'type' => 1,
                'unit' => 'WOH',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            36 =>
            array (
                'id' => '92181630',
                'name' => 'GM Tour and Mice',
                'alias' => 'General Manager Tour and Mice',
                'user_id' => '48658',
                'group_id' => NULL,
                'grade' => 'M1.2',
                'hierarchy' => 11,
                'type' => 1,
                'unit' => 'WOM',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            37 =>
            array (
                'id' => '92181631',
                'name' => 'GM Ticketing',
                'alias' => 'General Manager Ticketing',
                'user_id' => '42300',
                'group_id' => NULL,
                'grade' => 'M1.2',
                'hierarchy' => 17,
                'type' => 1,
                'unit' => 'WOT',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            38 =>
            array (
                'id' => '92181633',
                'name' => 'VP Corporate Secretary',
                'alias' => 'Vice President Corporate Secretary',
                'user_id' => '67754',
                'group_id' => NULL,
                'grade' => 'M1.2',
                'hierarchy' => 68,
                'type' => 1,
                'unit' => 'WUC',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            39 =>
            array (
                'id' => '92181634',
                'name' => 'M Internal Audit',
                'alias' => 'Manager Internal Audit',
                'user_id' => '46565',
                'group_id' => NULL,
                'grade' => 'M2.2',
                'hierarchy' => 80,
                'type' => 1,
                'unit' => 'WUIA',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            40 =>
            array (
                'id' => '92181639',
                'name' => 'M Business Development',
                'alias' => 'Manager Business Development',
                'user_id' => '47145',
                'group_id' => NULL,
                'grade' => 'M2.2',
                'hierarchy' => 75,
                'type' => 1,
                'unit' => 'WUCB',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            41 =>
            array (
                'id' => '92181642',
                'name' => 'M Information Technology',
                'alias' => 'Manager Information Technology',
                'user_id' => '11790011',
                'group_id' => NULL,
                'grade' => 'M2.2',
                'hierarchy' => 79,
                'type' => 1,
                'unit' => 'WUCI',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            42 =>
            array (
                'id' => '92181648',
                'name' => 'M Finance',
                'alias' => 'Manager Finance',
                'user_id' => '10760009',
                'group_id' => NULL,
                'grade' => 'M2.2',
                'hierarchy' => 56,
                'type' => 1,
                'unit' => 'WKFF',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            43 =>
            array (
                'id' => '92181649',
                'name' => 'AM Finance dan Taxation',
                'alias' => 'Assistant Manager Finance dan Taxation',
                'user_id' => '66431',
                'group_id' => NULL,
                'grade' => 'M3.2',
                'hierarchy' => 58,
                'type' => 1,
                'unit' => 'WKFF',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            44 =>
            array (
                'id' => '92181651',
                'name' => 'SS Lawang Sewu Historical Building',
                'alias' => 'Senior Supervisor Lawang Sewu Historical Building',
                'user_id' => '65566',
                'group_id' => NULL,
                'grade' => 'M4.1',
                'hierarchy' => 4,
                'type' => 1,
                'unit' => 'WOHM',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            45 =>
            array (
                'id' => '92181652',
                'name' => 'SS Indonesia Railway Museum Ambarawa',
                'alias' => 'Senior Supervisor Indonesia Railway Museum Ambarawa',
                'user_id' => '63773',
                'group_id' => NULL,
                'grade' => 'M4.1',
                'hierarchy' => 6,
                'type' => 1,
                'unit' => 'WOHM',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            46 =>
            array (
                'id' => '92181653',
                'name' => 'M Hospitality',
                'alias' => 'Manager Hospitality',
                'user_id' => '10680006',
                'group_id' => NULL,
                'grade' => 'M2.2',
                'hierarchy' => 8,
                'type' => 1,
                'unit' => 'WOHH',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            47 =>
            array (
                'id' => '92181660',
                'name' => 'M Ticketing',
                'alias' => 'Manager Ticketing',
                'user_id' => '45374',
                'group_id' => NULL,
                'grade' => 'M2.2',
                'hierarchy' => 24,
                'type' => 1,
                'unit' => 'WOTT',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            48 =>
            array (
                'id' => '92181661',
                'name' => 'AM Ticketing KAI dan GDS',
                'alias' => 'Assistant Manager Ticketing KAI dan GDS',
                'user_id' => '52375',
                'group_id' => NULL,
                'grade' => 'M3.2',
                'hierarchy' => 26,
                'type' => 1,
                'unit' => 'WOTT',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            49 =>
            array (
                'id' => '92181663',
                'name' => 'M Non Ticketing',
                'alias' => 'Manager Non Ticketing',
                'user_id' => '40878',
                'group_id' => NULL,
                'grade' => 'M2.2',
                'hierarchy' => 27,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            50 =>
            array (
                'id' => '92181677',
                'name' => 'M Human Capital',
                'alias' => 'Manager Human Capital',
                'user_id' => '45544',
                'group_id' => NULL,
                'grade' => 'M2.2',
                'hierarchy' => 64,
                'type' => 1,
                'unit' => 'WKFH',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            51 =>
            array (
                'id' => '92181678',
                'name' => 'AM Human Capital',
                'alias' => 'Assistant Manager Human Capital',
                'user_id' => '43310',
                'group_id' => NULL,
                'grade' => 'M3.2',
                'hierarchy' => 67,
                'type' => 1,
                'unit' => 'WKFH',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            52 =>
            array (
                'id' => '92182887',
                'name' => 'Adm Lawang Sewu',
                'alias' => 'Staf Adm Lawang Sewu',
                'user_id' => '19930294',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 5,
                'type' => 1,
                'unit' => 'WOHM',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            53 =>
            array (
                'id' => '92193600',
                'name' => 'Legal Specialist',
                'alias' => 'Legal Specialist',
                'user_id' => '19930305',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 73,
                'type' => 1,
                'unit' => 'WUCC',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            54 =>
            array (
                'id' => '92193685',
                'name' => 'Staf Tour Mice',
                'alias' => 'Staf Tour Mice',
                'user_id' => '19930175',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 13,
                'type' => 1,
                'unit' => 'WOMT',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            55 =>
            array (
                'id' => '92193686',
                'name' => 'Content Creator',
                'alias' => 'Content Creator',
                'user_id' => '19930172',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 76,
                'type' => 1,
                'unit' => 'WUCB',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            56 =>
            array (
                'id' => '92196226',
                'name' => 'HC Administration',
                'alias' => 'HC Administration',
                'user_id' => '19930178',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 65,
                'type' => 1,
                'unit' => 'WKFH',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            57 =>
            array (
                'id' => '92196227',
                'name' => 'Staf Luxury Train',
                'alias' => 'Staf Luxury Train',
                'user_id' => '19930177',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 33,
                'type' => 1,
                'unit' => 'WOL',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            58 =>
            array (
                'id' => '92196229',
                'name' => 'Ground Handling',
                'alias' => 'Ground Handling',
                'user_id' => '19930179',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 44,
                'type' => 1,
                'unit' => 'WOLO',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            59 =>
            array (
                'id' => '92196230',
                'name' => 'Ground Handling Bandung',
                'alias' => 'Ground Handling Bandung',
                'user_id' => '19930181',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 34,
                'type' => 1,
                'unit' => 'WOL',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            60 =>
            array (
                'id' => '92196232',
                'name' => 'Ground Handling',
                'alias' => 'Ground Handling',
                'user_id' => '19930183',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 53,
                'type' => 1,
                'unit' => 'WOLO',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            61 =>
            array (
                'id' => '92196234',
                'name' => 'Ground Handling Jakarta',
                'alias' => 'Ground Handling Jakarta',
                'user_id' => '19930185',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 35,
                'type' => 1,
                'unit' => 'WOL',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            62 =>
            array (
                'id' => '92196235',
                'name' => 'Ground Handling',
                'alias' => 'Ground Handling',
                'user_id' => '19930186',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 43,
                'type' => 1,
                'unit' => 'WOLO',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            63 =>
            array (
                'id' => '92196236',
                'name' => 'Ground Handling Jakarta',
                'alias' => 'Ground Handling Jakarta',
                'user_id' => '19930187',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 36,
                'type' => 1,
                'unit' => 'WOL',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            64 =>
            array (
                'id' => '92196257',
                'name' => 'Ground Handling Jakarta',
                'alias' => 'Ground Handling Jakarta',
                'user_id' => '19930188',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 37,
                'type' => 1,
                'unit' => 'WOL',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            65 =>
            array (
                'id' => '92196258',
                'name' => 'Train Attendant',
                'alias' => 'Train Attendant',
                'user_id' => '19930337',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 45,
                'type' => 1,
                'unit' => 'WOLO',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            66 =>
            array (
                'id' => '92196296',
                'name' => 'Train Attendant',
                'alias' => 'Train Attendant',
                'user_id' => '19930254',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 50,
                'type' => 1,
                'unit' => 'WOLO',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            67 =>
            array (
                'id' => '92196297',
                'name' => 'Train Attendant',
                'alias' => 'Train Attendant',
                'user_id' => '19930338',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 46,
                'type' => 1,
                'unit' => 'WOLO',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            68 =>
            array (
                'id' => '92196316',
                'name' => 'Train Attendant',
                'alias' => 'Train Attendant',
                'user_id' => '19930339',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 51,
                'type' => 1,
                'unit' => 'WOLO',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            69 =>
            array (
                'id' => '92196338',
                'name' => 'Train Attendant',
                'alias' => 'Train Attendant',
                'user_id' => '19930340',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 52,
                'type' => 1,
                'unit' => 'WOLO',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            70 =>
            array (
                'id' => '92196339',
                'name' => 'Train Attendant',
                'alias' => 'Train Attendant',
                'user_id' => '19930264',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 47,
                'type' => 1,
                'unit' => 'WOLO',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            71 =>
            array (
                'id' => '92196340',
                'name' => 'Train Attendant',
                'alias' => 'Train Attendant',
                'user_id' => '19930263',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 48,
                'type' => 1,
                'unit' => 'WOLO',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            72 =>
            array (
                'id' => '92196589',
                'name' => 'Plt Director of Finance dan Administration',
                'alias' => 'PLT Director of Finance dan Administration',
                'user_id' => '64813',
                'group_id' => NULL,
                'grade' => 'BOD.2',
                'hierarchy' => 54,
                'type' => 1,
                'unit' => 'WK',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            73 =>
            array (
                'id' => '92198137',
                'name' => 'Supervisor 1 Area 2',
                'alias' => 'Supervisor 1 Area 2',
                'user_id' => '64213',
                'group_id' => NULL,
                'grade' => 'M4.2',
                'hierarchy' => 101,
                'type' => 1,
                'unit' => 'WOMT',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            74 =>
            array (
                'id' => '92198215',
                'name' => 'JM Operation Tour and MICE',
                'alias' => 'Junior Manager Operation Tour and MICE',
                'user_id' => '19930246',
                'group_id' => NULL,
                'grade' => 'M3.1',
                'hierarchy' => 15,
                'type' => 1,
                'unit' => 'WOMT',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            75 =>
            array (
                'id' => '92198218',
                'name' => 'Staf Tour Mice',
                'alias' => 'Staf Tour Mice',
                'user_id' => '19930333',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 14,
                'type' => 1,
                'unit' => 'WOMT',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            76 =>
            array (
                'id' => '92198353',
                'name' => 'JS Sales Office',
                'alias' => 'Junior Supervisor Sales Office',
                'user_id' => '12880021',
                'group_id' => NULL,
                'grade' => 'M4.3',
                'hierarchy' => 82,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            77 =>
            array (
                'id' => '92198354',
                'name' => 'S Administration IRM Ambarawa',
                'alias' => 'Supervisor Administration IRM Ambarawa',
                'user_id' => '50258',
                'group_id' => NULL,
                'grade' => 'M4.2',
                'hierarchy' => 7,
                'type' => 1,
                'unit' => 'WOHM',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            78 =>
            array (
                'id' => '92198356',
                'name' => 'S 2 Area 4 Sumatera Barat',
                'alias' => 'Supervisor 2 Area 4 Sumatera Barat',
                'user_id' => '62340',
                'group_id' => NULL,
                'grade' => 'M4.2',
                'hierarchy' => 107,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            79 =>
            array (
                'id' => '92198360',
                'name' => 'AM Administration Tour and MICE',
                'alias' => 'Assistant Manager Administration Tour and MICE',
                'user_id' => '69224',
                'group_id' => NULL,
                'grade' => 'M3.2',
                'hierarchy' => 16,
                'type' => 1,
                'unit' => 'WOMT',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            80 =>
            array (
                'id' => '92198361',
                'name' => 'AM Legal',
                'alias' => 'Assistant Manager Legal',
                'user_id' => '66464',
                'group_id' => NULL,
                'grade' => 'M3.2',
                'hierarchy' => 72,
                'type' => 1,
                'unit' => 'WUCC',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            81 =>
            array (
                'id' => '92198363',
                'name' => 'AM General Affair',
                'alias' => 'Assistant Manager General Affair',
                'user_id' => '12840022',
                'group_id' => NULL,
                'grade' => 'M3.2',
                'hierarchy' => 74,
                'type' => 1,
                'unit' => 'WUCC',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            82 =>
            array (
                'id' => '92198581',
                'name' => 'Teknisi Kereta Wisata',
                'alias' => 'Teknisi Kereta Wisata',
                'user_id' => '19760161',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 31,
                'type' => 1,
                'unit' => 'WOL',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            83 =>
            array (
                'id' => '92199987',
                'name' => 'GM Luxury Coach',
                'alias' => 'General Manager Luxury Coach',
                'user_id' => '58219',
                'group_id' => NULL,
                'grade' => 'M1.2',
                'hierarchy' => 29,
                'type' => 1,
                'unit' => 'WOL',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            84 =>
            array (
                'id' => '92202242',
                'name' => 'Specalist Muda Ticketing',
                'alias' => 'Specalist Muda Ticketing',
                'user_id' => '10750004',
                'group_id' => NULL,
                'grade' => 'S3.2',
                'hierarchy' => 25,
                'type' => 1,
                'unit' => 'WOTT',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            85 =>
            array (
                'id' => '92202243',
                'name' => 'JS Operasional KCI',
                'alias' => 'Junior Supervisor Operasional KCI',
                'user_id' => '12750018',
                'group_id' => NULL,
                'grade' => 'M4.3',
                'hierarchy' => 28,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            86 =>
            array (
                'id' => '92202402',
                'name' => 'M Operation Luxury Coach',
                'alias' => 'Manager Operation Luxury Coach',
                'user_id' => '43925',
                'group_id' => NULL,
                'grade' => 'M2.2',
                'hierarchy' => 41,
                'type' => 1,
                'unit' => 'WOLO',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            87 =>
            array (
                'id' => '92202403',
                'name' => 'AM Crew Luxury Coach',
                'alias' => 'Assistant Manager Crew Luxury Coach',
                'user_id' => '49050',
                'group_id' => NULL,
                'grade' => 'M3.2',
                'hierarchy' => 40,
                'type' => 1,
                'unit' => 'WOLM',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            88 =>
            array (
                'id' => '92202404',
                'name' => 'AM Marketing and Sales Luxury Coach',
                'alias' => 'Assistant Manager Marketing and Sales Luxury Coach',
                'user_id' => '58196',
                'group_id' => NULL,
                'grade' => 'M3.2',
                'hierarchy' => 39,
                'type' => 1,
                'unit' => 'WOLM',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            89 =>
            array (
                'id' => '92202406',
                'name' => 'AM Rolling Stock Luxury Coach',
                'alias' => 'Assistant Manager Rolling Stock Luxury Coach',
                'user_id' => '48903',
                'group_id' => NULL,
                'grade' => 'M3.2',
                'hierarchy' => 42,
                'type' => 1,
                'unit' => 'WOLO',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            90 =>
            array (
                'id' => '92202409',
                'name' => 'M Corporate Communication',
                'alias' => 'Manager Corporate Communication',
                'user_id' => '45196',
                'group_id' => NULL,
                'grade' => 'M2.2',
                'hierarchy' => 71,
                'type' => 1,
                'unit' => 'WUCC',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            91 =>
            array (
                'id' => '92202816',
                'name' => 'Pengawas Lapangan Area 1 KCI',
                'alias' => 'Pengawas Lapangan Area 1 KCI',
                'user_id' => '19930252',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 81,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            92 =>
            array (
                'id' => '92202817',
                'name' => 'Pengawas Lapangan Area 1 KCI',
                'alias' => 'Pengawas Lapangan Area 1 KCI',
                'user_id' => '19930251',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 89,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            93 =>
            array (
                'id' => '92202900',
                'name' => 'Train Attendant',
                'alias' => 'Train Attendant',
                'user_id' => '19930261',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 49,
                'type' => 1,
                'unit' => 'WOLO',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            94 =>
            array (
                'id' => '92206427',
                'name' => 'Sekretaris Direksi',
                'alias' => 'Sekretaris Direksi',
                'user_id' => '19930266',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 19,
                'type' => 1,
                'unit' => 'WOT',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            95 =>
            array (
                'id' => '92207024',
                'name' => 'Pengawas Lapangan Area 3 Daop 7',
                'alias' => 'Pengawas Lapangan Area 3 Daop 7',
                'user_id' => '19930279',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 102,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            96 =>
            array (
                'id' => '92207034',
                'name' => 'Pengawas Lapangan Area 2 Daop 4',
                'alias' => 'Pengawas Lapangan Area 2 Daop 4',
                'user_id' => '19930274',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 92,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            97 =>
            array (
                'id' => '92207376',
                'name' => 'PLT President Director',
                'alias' => 'PLT President Director',
                'user_id' => '46921',
                'group_id' => NULL,
                'grade' => 'BOD.2',
                'hierarchy' => 1,
                'type' => 1,
                'unit' => 'WU',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            98 =>
            array (
                'id' => '92209818',
                'name' => 'Koordinator CC121',
                'alias' => 'Koordinator CC121',
                'user_id' => '19930295',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 85,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            99 =>
            array (
                'id' => '92211607',
                'name' => 'Senior Specialist Alih Daya Non Sta',
                'alias' => 'Senior Specialist Alih Daya Non Sta',
                'user_id' => '19930306',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 18,
                'type' => 1,
                'unit' => 'WOT',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            100 =>
            array (
                'id' => '92211887',
                'name' => 'Graphic Designer',
                'alias' => 'Graphic Designer',
                'user_id' => '19930307',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 77,
                'type' => 1,
                'unit' => 'WUCB',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            101 =>
            array (
                'id' => '92212620',
                'name' => 'PLT VP Finance and Administration',
                'alias' => 'PLT Vice President Finance and Administration',
                'user_id' => '46573',
                'group_id' => NULL,
                'grade' => 'M1.2',
                'hierarchy' => 55,
                'type' => 1,
                'unit' => 'WKF',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            102 =>
            array (
                'id' => '92213246',
                'name' => 'Pengawas Lapangan Area 2 Daop 6',
                'alias' => 'Pengawas Lapangan Area 2 Daop 6',
                'user_id' => '19930313',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 96,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            103 =>
            array (
                'id' => '92213638',
                'name' => 'Pengawas Lapangan Area 4 Divre III',
                'alias' => 'Pengawas Lapangan Area 4 Divre III',
                'user_id' => '19930323',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 109,
                'type' => 1,
                'unit' => 'WOTN',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            104 =>
            array (
                'id' => '92213863',
                'name' => 'Staf Luxury Train',
                'alias' => 'Staf Luxury Train',
                'user_id' => '19930322',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 38,
                'type' => 1,
                'unit' => 'WOL',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            105 =>
            array (
                'id' => '92219451',
                'name' => 'Adm Hospitality',
                'alias' => 'Staf Adm Hospitality',
                'user_id' => '19930332',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 10,
                'type' => 1,
                'unit' => 'WOHH',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            106 =>
            array (
                'id' => '92219452',
                'name' => 'Hotel Manager',
                'alias' => 'Hotel Manager',
                'user_id' => '19930335',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 9,
                'type' => 1,
                'unit' => 'WOHH',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            107 =>
            array (
                'id' => '92219453',
                'name' => 'Pengawas Lapangan',
                'alias' => 'Pengawas Lapangan',
                'user_id' => '19930328',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 20,
                'type' => 1,
                'unit' => 'WOT',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            108 =>
            array (
                'id' => '92219454',
                'name' => 'Pengawas Lapangan Surabaya',
                'alias' => 'Pengawas Lapangan Surabaya',
                'user_id' => '19930329',
                'group_id' => NULL,
                'grade' => 'E.',
                'hierarchy' => 23,
                'type' => 1,
                'unit' => 'WOT',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            109 =>
            array (
                'id' => '92219712',
                'name' => 'M Finance & Taxation',
                'alias' => 'Manager Finance & Taxation',
                'user_id' => '46116',
                'group_id' => NULL,
                'grade' => 'M2.2',
                'hierarchy' => 59,
                'type' => 1,
                'unit' => 'WKFC',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            110 =>
            array (
                'id' => '92219716',
                'name' => 'S Cash',
                'alias' => 'Supervisor Cash',
                'user_id' => '12890019',
                'group_id' => NULL,
                'grade' => 'M4.2',
                'hierarchy' => 62,
                'type' => 1,
                'unit' => 'WKFC',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            111 =>
            array (
                'id' => '97000001',
                'name' => 'Seluruh Pekerja',
                'alias' => 'Seluruh Pekerja',
                'user_id' => '',
                'group_id' => 1,
                'grade' => '',
                'hierarchy' => 1,
                'type' => 2,
                'unit' => 'ALL',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            112 =>
            array (
                'id' => '97000002',
                'name' => 'Direksi PT Kereta Api Pariwisata',
                'alias' => 'Direksi PT Kereta Api Pariwisata',
                'user_id' => '',
                'group_id' => 2,
                'grade' => '',
                'hierarchy' => 2,
                'type' => 2,
                'unit' => 'Management',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            113 =>
            array (
                'id' => '97000003',
                'name' => 'Para Manager',
                'alias' => 'Para Manager',
                'user_id' => '',
                'group_id' => 3,
                'grade' => '',
                'hierarchy' => 3,
                'type' => 2,
                'unit' => 'Management',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            114 =>
            array (
                'id' => '97000004',
                'name' => 'Para Vice President / General manager',
                'alias' => 'Para Vice President / General manager',
                'user_id' => '',
                'group_id' => 4,
                'grade' => '',
                'hierarchy' => 4,
                'type' => 2,
                'unit' => 'Management',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            115 =>
            array (
                'id' => '97000005',
                'name' => 'Para Junior Manager / Assistant Manager',
                'alias' => 'Para Junior Manager / Assistant Manager',
                'user_id' => '',
                'group_id' => 5,
                'grade' => '',
                'hierarchy' => 5,
                'type' => 2,
                'unit' => 'Management',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            116 =>
            array (
                'id' => '97000006',
                'name' => 'Para SeniorSupervisor / Supervisor /Junior Supervi',
                'alias' => 'Para SeniorSupervisor / Supervisor /Junior Supervi',
                'user_id' => '',
                'group_id' => 6,
                'grade' => '',
                'hierarchy' => 6,
                'type' => 2,
                'unit' => 'Management',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            117 =>
            array (
                'id' => '97000007',
                'name' => 'Para Manager di WKF',
                'alias' => 'Para Manager di WKF',
                'user_id' => '',
                'group_id' => 7,
                'grade' => '',
                'hierarchy' => 7,
                'type' => 2,
                'unit' => 'WKF',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            118 =>
            array (
                'id' => '97000009',
                'name' => 'Para Junior Manager / Assistant Manager di WKF',
                'alias' => 'Para Junior Manager / Assistant Manager di WKF',
                'user_id' => '',
                'group_id' => 9,
                'grade' => '',
                'hierarchy' => 8,
                'type' => 2,
                'unit' => 'WKF',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            119 =>
            array (
                'id' => '97000010',
                'name' => 'Para Supervisor di WKF',
                'alias' => 'Para Supervisor di WKF',
                'user_id' => '',
                'group_id' => 10,
                'grade' => '',
                'hierarchy' => 9,
                'type' => 2,
                'unit' => 'WKF',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            120 =>
            array (
                'id' => '97000011',
                'name' => 'Para Manager di WUC',
                'alias' => 'Para Manager di WUC',
                'user_id' => '',
                'group_id' => 11,
                'grade' => '',
                'hierarchy' => 10,
                'type' => 2,
                'unit' => 'WUC',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            121 =>
            array (
                'id' => '97000013',
                'name' => 'Para Junior Manager / Assistant Manager di WUC',
                'alias' => 'Para Junior Manager / Assistant Manager di WUC',
                'user_id' => '',
                'group_id' => 13,
                'grade' => '',
                'hierarchy' => 11,
                'type' => 2,
                'unit' => 'WUC',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            122 =>
            array (
                'id' => '97000014',
                'name' => 'Para Supervisor di WUC',
                'alias' => 'Para Supervisor di WUC',
                'user_id' => '',
                'group_id' => 14,
                'grade' => '',
                'hierarchy' => 12,
                'type' => 2,
                'unit' => 'WUC',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            123 =>
            array (
                'id' => '97000015',
                'name' => 'Para Manager di WOT',
                'alias' => 'Para Manager di WOT',
                'user_id' => '',
                'group_id' => 15,
                'grade' => '',
                'hierarchy' => 13,
                'type' => 2,
                'unit' => 'WOT',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            124 =>
            array (
                'id' => '97000017',
                'name' => 'Para Junior Manager / Assistant Manager di WOT',
                'alias' => 'Para Junior Manager / Assistant Manager di WOT',
                'user_id' => '',
                'group_id' => 17,
                'grade' => '',
                'hierarchy' => 14,
                'type' => 2,
                'unit' => 'WOT',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            125 =>
            array (
                'id' => '97000018',
                'name' => 'Para Supervisor di WOT',
                'alias' => 'Para Supervisor di WOT',
                'user_id' => '',
                'group_id' => 18,
                'grade' => '',
                'hierarchy' => 15,
                'type' => 2,
                'unit' => 'WOT',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            126 =>
            array (
                'id' => '97000019',
                'name' => 'Para Manager di WOL',
                'alias' => 'Para Manager di WOL',
                'user_id' => '',
                'group_id' => 19,
                'grade' => '',
                'hierarchy' => 16,
                'type' => 2,
                'unit' => 'WOL',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            127 =>
            array (
                'id' => '97000021',
                'name' => 'Para Junior Manager / Assistant Manager di WOL',
                'alias' => 'Para Junior Manager / Assistant Manager di WOL',
                'user_id' => '',
                'group_id' => 21,
                'grade' => '',
                'hierarchy' => 17,
                'type' => 2,
                'unit' => 'WOL',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            128 =>
            array (
                'id' => '97000022',
                'name' => 'Para Supervisor di WOL',
                'alias' => 'Para Supervisor di WOL',
                'user_id' => '',
                'group_id' => 22,
                'grade' => '',
                'hierarchy' => 18,
                'type' => 2,
                'unit' => 'WOL',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            129 =>
            array (
                'id' => '97000023',
                'name' => 'Para Manager di WOH',
                'alias' => 'Para Manager di WOH',
                'user_id' => '',
                'group_id' => 23,
                'grade' => '',
                'hierarchy' => 19,
                'type' => 2,
                'unit' => 'WOH',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            130 =>
            array (
                'id' => '97000025',
                'name' => 'Para Junior Manager / Assistant Manager di WOH',
                'alias' => 'Para Junior Manager / Assistant Manager di WOH',
                'user_id' => '',
                'group_id' => 25,
                'grade' => '',
                'hierarchy' => 20,
                'type' => 2,
                'unit' => 'WOH',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            131 =>
            array (
                'id' => '97000026',
                'name' => 'Para Supervisor di WOH',
                'alias' => 'Para Supervisor di WOH',
                'user_id' => '',
                'group_id' => 26,
                'grade' => '',
                'hierarchy' => 21,
                'type' => 2,
                'unit' => 'WOH',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            132 =>
            array (
                'id' => '97000027',
                'name' => 'Para Manager di WOM',
                'alias' => 'Para Manager di WOM',
                'user_id' => '',
                'group_id' => 27,
                'grade' => '',
                'hierarchy' => 22,
                'type' => 2,
                'unit' => 'WOM',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            133 =>
            array (
                'id' => '97000029',
                'name' => 'Para Junior Manager / Assistant Manager di WOM',
                'alias' => 'Para Junior Manager / Assistant Manager di WOM',
                'user_id' => '',
                'group_id' => 29,
                'grade' => '',
                'hierarchy' => 23,
                'type' => 2,
                'unit' => 'WOM',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            134 =>
            array (
                'id' => '97000030',
                'name' => 'Para Supervisor di WOM',
                'alias' => 'Para Supervisor di WOM',
                'user_id' => '',
                'group_id' => 30,
                'grade' => '',
                'hierarchy' => 24,
                'type' => 2,
                'unit' => 'WOM',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            135 =>
            array (
                'id' => '97000031',
                'name' => 'Para Pelaksana Organik',
                'alias' => 'Para Pelaksana Organik',
                'user_id' => '',
                'group_id' => 31,
                'grade' => '',
                'hierarchy' => 25,
                'type' => 2,
                'unit' => 'ALL',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            136 =>
            array (
                'id' => '97000032',
                'name' => 'Para PKWT',
                'alias' => 'Para PKWT',
                'user_id' => '',
                'group_id' => 32,
                'grade' => '',
                'hierarchy' => 26,
                'type' => 2,
                'unit' => 'ALL',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            137 =>
            array (
                'id' => '97000033',
                'name' => 'Para Pengawas Lapangan',
                'alias' => 'Para Pengawas Lapangan',
                'user_id' => '',
                'group_id' => 33,
                'grade' => '',
                'hierarchy' => 27,
                'type' => 2,
                'unit' => 'ALL',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            138 =>
            array (
                'id' => '97000034',
                'name' => 'Para Pelaksana di WKF',
                'alias' => 'Para Pelaksana di WKF',
                'user_id' => '',
                'group_id' => 34,
                'grade' => '',
                'hierarchy' => 28,
                'type' => 2,
                'unit' => 'WKF',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            139 =>
            array (
                'id' => '97000035',
                'name' => 'Para Pelaksana di WOL',
                'alias' => 'Para Pelaksana di WOL',
                'user_id' => '',
                'group_id' => 35,
                'grade' => '',
                'hierarchy' => 29,
                'type' => 2,
                'unit' => 'WOL',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            140 =>
            array (
                'id' => '97000036',
                'name' => 'Para Pelaksana di WOH',
                'alias' => 'Para Pelaksana di WOH',
                'user_id' => '',
                'group_id' => 36,
                'grade' => '',
                'hierarchy' => 30,
                'type' => 2,
                'unit' => 'WOH',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            141 =>
            array (
                'id' => '97000037',
                'name' => 'Para Pelaksana di WUC',
                'alias' => 'Para Pelaksana di WUC',
                'user_id' => '',
                'group_id' => 37,
                'grade' => '',
                'hierarchy' => 31,
                'type' => 2,
                'unit' => 'WUC',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            142 =>
            array (
                'id' => '97000038',
                'name' => 'Para Pelaksana di WOT',
                'alias' => 'Para Pelaksana di WOT',
                'user_id' => '',
                'group_id' => 38,
                'grade' => '',
                'hierarchy' => 32,
                'type' => 2,
                'unit' => 'WOT',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
            143 =>
            array (
                'id' => '97000039',
                'name' => 'Para Pelaksana di WOM',
                'alias' => 'Para Pelaksana di WOM',
                'user_id' => '',
                'group_id' => 39,
                'grade' => '',
                'hierarchy' => 33,
                'type' => 2,
                'unit' => 'WOM',
                'created_at' => '2022-04-04 00:00:00',
                'updated_at' => '2022-04-04 00:00:00',
            ),
        ));


    }
}
